name: My Starter Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  call-workflow-in-local-repo:
    uses: Shrikant43/githubactionsdemo/.github/workflows/resuable-workflow-1.yml@main
    with:
      node: 8
