name: resuable workflow 1

on: 
  workflow_call:

jobs:

  ru1-job1:
  
     runs-on: ubuntu-lates
  
     steps: 

         - uses: actions/checkout@v3

         - name: write something in log such as hello world

               echo "I am resuable workflow 1 here called"
