name: resuable workflow 1

on: 
  workflow_call:

jobs:

  ru1-job1:
  
     runs-on: ubuntu-latest
  
     steps: 

         - uses: actions/checkout@v3

         - name: write something in log

               echo "I am resuable workflow 1 here called"
